package it.unibo.papasburgeria.model.api;

import it.unibo.papasburgeria.model.IngredientEnum;

import java.util.List;

/**
 * Models how the lines work.
 */
public interface RegisterModel {

    /**
     * Starts a new customer thread and kills the previous one.
     *
     * @param delay                defines the rate at which customer arrives
     * @param customerAmount       defines how many customers will be generated by the thread
     * @param availableIngredients defines the possible ingredients in the orders
     */
    void startCustomerThread(int delay, int customerAmount, List<IngredientEnum> availableIngredients);

    /**
     * Stops the customers from arriving.
     */
    void killCustomerThread();

    /**
     * Adds a customer to the register line.
     *
     * @param customer Customer added to end of register line.
     */
    void addCustomerRegisterLine(Customer customer);

    /**
     * Removes a customer from the register line.
     *
     * @param customer Customer added to end of register line.
     */
    void removeCustomerRegisterLine(Customer customer);

    /**
     * Adds a customer to the wait line.
     *
     * @param customer Customer added to end of wait line.
     */
    void addCustomerWaitLine(Customer customer);

    /**
     * Removes a customer from the register line.
     *
     * @param customer Customer removed from wait line.
     */
    void removeCustomerWaitLine(Customer customer);

    /**
     * Empties the Register line.
     */
    void clearRegisterLine();

    /**
     * Empties the Wait line.
     */
    void clearWaitLine();

    /**
     * Empties both lines.
     */
    void clearLines();

    /**
     * Get the customer thread status.
     *
     * @return true if the customer thread is alive.
     */
    boolean isCustomerThreadStatus();

    /**
     * Get the register line.
     *
     * @return the register line.
     */
    List<Customer> getRegisterLine();

    /**
     * Get the register line.
     *
     * @return the wait line
     */
    List<Customer> getWaitLine();
}
