package it.unibo.papasburgeria.model.api;

import java.util.List;

import it.unibo.papasburgeria.model.IngredientEnum;

/**
 * models how the lines work.
 */
public interface RegisterModel {

    /**
     * @param delay                defines the rate at which customer arrives
     * @param customerAmount       defines how many customers will be generated by the thread
     * @param availableIngredients defines the possible ingredients in the orders
     */
    void startCustomerThread(int delay, int customerAmount, List<IngredientEnum> availableIngredients);

    /**
     * stops the customers from arriving.
     */
    void killCustomerThread();

    /**
     * @return first customer of register line.
     */
    Customer popCustomerRegisterLine();

    /**
     * @param customer Customer added to end of register line.
     */
    void pushCustomerRegisterLine(Customer customer);

    /**
     * @param customer Customer added to end of register line.
     */
    void removeCustomerRegisterLine(Customer customer);

    /**
     * @return first customer of wait line.
     */
    Customer popCustomerWaitLine();

    /**
     * @param customer Customer added to end of wait line.
     */
    void pushCustomerWaitLine(Customer customer);

    /**
     * @param customer Customer removed from wait line.
     */
    void removeCustomerWaitLine(Customer customer);

    /**
     * Empties the Register line.
     */
    void clearRegisterLine();

    /**
     * Empties the Wait line.
     */
    void clearWaitLine();

    /**
     * Empties both lines.
     */
    void clearLines();

    /**
     * @return the register line
     */
    List<Customer> getRegisterLine();

    /**
     * @return the wait line
     */
    List<Customer> getWaitLine();
}
